server:
  port: 9003


spring:
  application:
    name: service-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://service1.hurrican.cn:9000/eureka/
  instance:
    prefer-ip-address: true