server:
  port: 9004


spring:
  application:
    name: service-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://service1.hurrican.cn:9001/eureka/
  instance:
    prefer-ip-address: true