spring:
  application:
    name: eurka-cluster-server
#  security:
#    basic:
#      enabled: true
#    user:
#      name: admin
#      password: 654321

---
spring:
  profiles: hurrican1
server:
  port: 9000
eureka:
  instance:
    hostname: service1.hurrican.cn
  client:
    serviceUrl:
      defaultZone: http://service2.hurrican.cn:9001/eureka/

---
spring:
  profiles: hurrican2
server:
  port: 9001
eureka:
  instance:
    hostname: service2.hurrican.cn
  client:
    serviceUrl:
      defaultZone: http://service1.hurrican.cn:9000/eureka/

